version: "2"
services:
    server:
        build: .
        restart: always
        ports:
            - "8090:8090"
        environment:
            - MONGODB_URI=mongodb://mongo:27017/rc4git
        volumes:
            - ./:/rc4git
        networks:
            - dbnet

networks:
    dbnet:
        external: true